### ISSUE TITLE
make test-snapshot includes missing

### ISSUE THREAD

**Issue by franziskuskiefer** [mitls/hacl-star#27] opened 2017-08-08 12:14 UTC
I tried to run the tests with `test-snapshot` but it looks like some includes are missing. Extraction works fine, but the tests don't compile.

    gcc -flto -std=c11 -D_GNU_SOURCE -Ofast -march=native -mtune=native -m64 -fwrapv -fomit-frame-pointer -funroll-loops -I ../../other_providers/openssl -I ../../other_providers/openssl/include -I ../../other_providers/openssl/crypto/ec -I ../../other_providers/openssl/crypto/include -I ../../other_providers/openssl/crypto/poly1305 -I ../../other_providers/libsodium/src/libsodium/include -L../../other_providers/libsodium/src/libsodium/lib -I ../../other_providers/tweetnacl \
      ../../other_providers/tweetnacl/tweetnacl.c \
      kremlib.c testlib.c Poly1305_64.c test-poly.c -o test-poly.exe \
      -lsodium ../../other_providers/openssl/libcrypto.a
    In file included from FStar.h:9:0,
                     from Poly1305_64.h:7,
                     from Poly1305_64.c:1:
    Chacha20.h:41:33: error: unknown type name 'FStar_Monotonic_HyperStack_mem'
    void *Chacha20_op_String_Access(FStar_Monotonic_HyperStack_mem h, uint8_t *m);

**Comment by beurdouche** [comment] 2017-08-15 17:55
This has been fixed in master, can't reproduce anymore

**Closed by beurdouche** 2017-08-15 17:55 UTC
